# Generated by Django 5.2.1 on 2025-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement_frais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='lieu_naissance_elev',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
